### ISSUE TITLE
sometimes navtree databases are missing

### ISSUE THREAD

**Issue by jchris** [fauna/dashboard#102]
sometimes on a fresh page load, even after it does the right network queries, the screen is missing the database tree.

<img width="972" alt="screen shot 2017-01-20 at 2 39 47 pm" src="https://cloud.githubusercontent.com/assets/253/22167985/903755e8-df1e-11e6-90da-da32f5283ce2.png">

**Comment by erickpintor** [comment]
I haven't seen this in the new dashboard. We can open it again if stumble upon this scenario again.
