### ISSUE TITLE
server keys not working in production environment

### ISSUE THREAD

**Issue by jchris** [fauna/dashboard#125]
when I use localhost, I can browse cloud using a server key, but when running on https://dashboard.fauna.com/db I get this error `invalid ref` when I click "Use Secret" in the login form

**Comment by marrony** [comment]
shouldn't be admin keys?

**Comment by jchris** [comment]
admin keys work great. Its just that server keys aren't working for me in production, but they do work in localhost.

**Comment by jchris** [comment]
With a server key you can interact with all the classes and indexes in your database, but there is no database tree.

<img width="1144" alt="screen shot 2017-01-24 at 2 33 04 pm" src="https://cloud.githubusercontent.com/assets/253/22269869/0c3529ec-e242-11e6-930b-020deec6a589.png">

**Comment by jchris** [comment]
eventually I'd like to add support for instance keys, also

**Comment by marrony** [comment]
With new dashboard this is not happening anymore

**Comment by erickpintor** [comment]
Fixed.
