### ISSUE TITLE
key management basics

### ISSUE THREAD

**Issue by jchris** [fauna/dashboard#138]
Right now the REPL operates with a server key so it can't manage keys.

We need some key management in the UI, at least the ability to create keys inside a database (this would go on the same form as deleting the database).

I need this to support the serverless.com integration I'm working on.

**Comment by jchris** [comment]
bah I haven't got to this yet but it keeps coming up. It occurs to me one way to MVP features is instead of coding a form just put in place text instructions for how to use an example query in the Query Console.

**Comment by erickpintor** [comment]
The new console can run queries with admin privileges, if that helps.

**Comment by jchris** [comment]
That does help. It would be a nice to have for launch, the ability to generate a server key for a database. Because all the README usage examples floating out there ask you to create a server key.
