### ISSUE TITLE
there should be a link in the credentials form to refresh login from your fauna.com session

### ISSUE THREAD

**Issue by jchris** [fauna/dashboard#168]
If you log out the dashboard, but you are still logged into Fauna.com, and you don't have a custom secret you want to use, you should be able to click a link to https://fauna.com/serverless-cloud-sign-up and get bounced back into the dashboard logged in.

**Comment by erickpintor** [comment]
I think this is a bug. If you're logged in at fauna.com you are supposed to have a cookie set that the dashboard would use to identify the user and seamless log you in. If you logout from the dashboard, you were also supposed to be logged out of fauna.com.

What are the steps you're using to reproduce this? Just a logout?

**Comment by jchris** [comment]
I think I'm starting my trip the dashboard.fauna.com when I'm logged out of fauna.com, and then using a custom secret to log in. But then later when I want to move to my fauna account secret, I have to remember the magic URL, instead of clicking a link that will bounce me back in.
