### ISSUE TITLE
Upgrade fauna js driver to 0.2.3

### ISSUE THREAD

**Issue by erickpintor** [fauna/dashboard#172]
It has the new `KeyFromSecret` function that will help us avoid some workarounds at the key type discovery process.

**Comment by erickpintor** [comment]
Done by https://github.com/fauna/dashboard/pull/173

**Comment by marrony** [comment]
This PR is upgrading `faunadb` to `0.2.2` and this version doesn't have `KeyFromSecret` yet

**Comment by erickpintor** [comment]
There is something wrong. The driver never had a `0.2.1` version. I think its getting the most recent version always because I can use the function `KeyFromSecret` normally.

**Comment by erickpintor** [comment]
Maybe we should change to use a fixed version of the driver.

**Comment by marrony** [comment]
I see that we're using `^0.2.2` so I did an `npm install` and it doesn't updated to the latest version. Then I deleted my `node_modules` and installed it again and it fetches the latest version. IDK how to proceed to always get the latest versions.

**Comment by erickpintor** [comment]
Maybe it's just `0.2.3` to use the exact number?

**Comment by marrony** [comment]
idiot, just use `npm update` 🤦‍♂️

**Comment by erickpintor** [comment]
Sure, but. Is it still possible to fix the version? I think we want to have more control of that because we need to update the functions list on every driver upgrade.

**Comment by marrony** [comment]
yeah, lets use fixed versions, it'll safer for us and potentially avoid some headaches.
