### ISSUE TITLE
REPL should allow multiline statements

### ISSUE THREAD

**Issue by jchris** [fauna/dashboard#192]
This works in the old REPL but not the new one:

```js
var matcher = q.Match(q.Ref("indexes/all_ace"));
q.Get(matcher);
```

**Comment by erickpintor** [comment]
This will be a little tricky and we may need a library to parse the js code the user wants to execute.
The reason why it's not working now is because we made the repl accept literal objects like:

```js
{
  classes: q.Paginate(q.Ref("classes")),
  indexes: q.Paginate(q.Ref("indexes"))
}
```

Which didn't work before because `eval` thinks `{}` are function bodies.
