### ISSUE TITLE
note on key management page about containment

### ISSUE THREAD

**Issue by jchris** [fauna/dashboard#201]
My inclination was to browse to a database, and then create a key for it. But really you need to browse to the database's containing database to create a key for it? Maybe we can hide this complexity from the user and let them make keys inside their database?

If not then we should put a note that says "you want to browse to the parent database"

**Comment by erickpintor** [comment]
I personally prefer to be informative about the containment. IMO, the UI should not induce people to believe that keys are located at the db level instead of its parent.

**Comment by jchris** [comment]
That's my concern also. Not too opinionated either way, so I think the note is good for now, and we'll see if users are still confused.

**Comment by freels** [comment]
Ah, I added this comment to the PR, but not the issue. It's on our roadmap to fix this at the core level, to make keys belong to the database they provide access to.
