### ISSUE TITLE
Error on `Manage Keys`

### ISSUE THREAD

**Issue by marrony** [fauna/dashboard#221]
The following error are returned when we select `Manage Keys`:

```json
{"errors":[{"position":["map","expr","in"],"code":"invalid expression","description":"No form/function found, or invalid argument keys: { lambda, expr }."}]}
```

**Comment by erickpintor** [comment]
Could you try to simulate this after a `npm update`? That sounds driver related.

**Comment by marrony** [comment]
Yeah, updating the driver solved the problem. Strange enough I validated the PR that introduced that feature and it worked that time

**Comment by erickpintor** [comment]
¯\_(ツ)_/¯
