### ISSUE TITLE
Dashboard URL should be first-class signup page

### ISSUE THREAD

**Issue by jchris** [fauna/dashboard#228]
There are links to https://dashboard.fauna.com all over the web. Currently it looks like this for new users:

![screen shot 2017-05-08 at 4 59 28 pm](https://cloud.githubusercontent.com/assets/253/25830169/e3493346-340f-11e7-89f8-5ceb0ec1a8bf.png)

Its first job should be to support new user sign up, but it would be nice to keep supporting the ability to log in with arbitrary keys and API endpoint URLs.

**Comment by jchris** [comment]
this one impacts sign up friction. fixing it is an opportunity for really smooth onramping.

**Comment by erickpintor** [comment]
Since last deploy, the dashboard redirects to the login page when there is no logged in user.
