### ISSUE TITLE
index definition widget

### ISSUE THREAD

**Issue by jchris** [fauna/dashboard#24]
The form for defining an index currently requires the user to type JSON field paths and stuff by hand. It would be really cool to have a UI-driven interface here. In the best case it would be self-documenting. Eg, using the UI would expose you to the different index options in a way that meant you didn't need to refer to the docs.

The Fabric components we are using include some widgets that might be helpful, [here are examples.](https://dev.office.com/fabric#/components/pickers) 

Here's the UI as it looks today, and [here is the code that implements it](https://github.com/faunadb/dashboard/blob/master/src/IndexForm.js#L78)

<img width="778" alt="screen shot 2016-12-18 at 6 25 53 pm" src="https://cloud.githubusercontent.com/assets/253/21299429/76cf9080-c550-11e6-9b65-1e6bb150b963.png">

**Comment by jchris** [comment]
In the deep future this feature could blossom into a full grown data-patterns-wizard https://github.com/faunadb/dashboard/issues/9 just to keep in mind for inspiration on the horizon

**Comment by jchris** [comment]
@marrony this one doesn't overlap with anything I might get into in the next couple of weeks, so it'd be a great place to jump in.

**Comment by jchris** [comment]
This is a great spot to hide the `"data"` noise in the field paths from users, we can just make the data and ref/ts fields distinct in the UI without the user having to deal with JSON wire format considerations.

**Comment by freels** [comment]
Design here needs to take into account the index definition changes we are planning on.

**Comment by erickpintor** [comment]
I didn't realized we have this ticket. When I moved the old index definition widget to the new dash I've removed the JSON fields and added a "tag like" component:

![image](https://cloud.githubusercontent.com/assets/813042/23723602/938612dc-0428-11e7-821e-344ee2727200.png)


Is that sufficient?
