### ISSUE TITLE
Issue with dashboard and admin key

### ISSUE THREAD

**Issue by jonniebigodes** [fauna/dashboard#293]
I've been using fauna for a little bit, trying to know how it works, liking it so far. 
But while developing a node.js app that consumes data stored with fauna. I'm experiencing a issue.
Going to elaborate on it. 

- Created an account without any issues, i used the github as a provider for authentication.
- Went to dashboard and i've setup a database. So that in the future i could use it.
- In the dashboard i went to the account settings checked that i had a api key, but i wasn't able to get the secret to be used with the client as per documentation. I then created a new api key with a random name, saw that the secret was shown, grabbed it and added it to my code.
- Tested it out and it was working as it should. 

 Now here's where the issue pops in.  After a couple  of hours, to the next day, running my code would throw the following error:
```bash
   Unauthorized: unauthorized
```
- Logged into fauna's dashboard and i'm presented with the following:
![fauna_key_error_corrected](https://user-images.githubusercontent.com/22988955/55898176-f7718480-5bb9-11e9-9d80-99278229e4b6.png)

The key's values are ommited for obvious reasons. But both entries are the same.
My question is the following, is this a dashboard issue, not communicating correctly with the backend? Or another unrelated issue.  This leads to having to constantly generating keys, wich in turn will be revoked and the dashboard will revert back to the image above.
This makes the development quite cumbersome.

**Comment by BrunoQuaresma** [comment]
Hi @jonniebigodes we deployed a fix on the last week. Can you confirm please if it is working good?

**Comment by jonniebigodes** [comment]
@BrunoQuaresma sorry for the "radio silence"(pardon the bad pun), it's been a hectic couple of weeks. Thank you for the feedback. By the time you read this it'll be closed, i've further tested it and all looks good. No more issues.
