### ISSUE TITLE
Local faunadb + dashboard, howto

### ISSUE THREAD

**Issue by zeusdeux** [fauna/dashboard#294]
Hi folks!

How does one use the dashboard with a local faunadb container?
I have tried running the container and exposed the api endpoint (on `0.0.0.0:8443`) with the secret as the default (`secret`).
Then I try to use the endpoint as `http://0.0.0.0:8443` and secret as `secret`, the dashboard times out on the POST request it makes to create some sort of a temp db.

Any idea what might be up?

**Comment by evbruno** [comment]
Let's go by parts, as Jack said:
- you can run the faunadb with: 
`docker run -p 8443:8443 fauna/faunadb` 
...wait until `FaunaDB is ready` shows
- verify that the db is up and running: 
```curl http://localhost:8443/ping
{ "resource": "Scope write is OK" }```
- now you can run the dashboard and try with the endpoint `http://localhost:8443` and secret `secret`

**Comment by zeusdeux** [comment]
Hey @evbruno!

I was doing exactly this but for some reason I was seeing a write failure in `query.log`.
I reset my local db and things started to work again! 

Thanks!
