### ISSUE TITLE
index detail layout

### ISSUE THREAD

**Issue by jchris** [fauna/dashboard#4]
Currently the index details view takes up a lot of space on the screen for how much information it gives you. A well rendered index info / terms / values screen would be compact and readable, leaving plenty of room for index row browsing and instance previews below the index details.

**Comment by jchris** [comment]
related https://github.com/faunadb/dashboard/issues/12
and https://github.com/faunadb/dashboard/issues/21

**Comment by erickpintor** [comment]
It has become a little bit better:

![image](https://cloud.githubusercontent.com/assets/813042/23723967/e2633b40-0429-11e7-82af-e38163d7e890.png)


But for further improvement, we'll need input from someone with UI experience.

**Comment by jchris** [comment]
lets close this and file it under "things a design agency would help with"
