### ISSUE TITLE
Backhaul client-side exceptions

### ISSUE THREAD

**Issue by eaceaser** [fauna/dashboard#52]

**Comment by jchris** [comment]
if we're logging exceptions back to the server, we should at least also log the router path and maybe some user actions along the same path. So it's not just crash reporting is usage telemetry. 

Everything but the exceptions is close enough to Google Analytics territory it almost makes me want to use GA for the crash reporting also.

**Comment by jchris** [comment]
When I add notes like the above, I'm not trying to expand scope of the current ticket, just give hints to implementers about the direction the feature might be going.

**Comment by erickpintor** [comment]
Do we still want to do this? What's its priority?

**Comment by eaceaser** [comment]
we definitely should do this. I'd say that its a relatively high priority, as I'm a bit loathe to deploy more features to customers without being able to get some kind of insight into exceptions and issues customers are facing.

**Comment by erickpintor** [comment]
There are two options as far as I can see right now:
- we can pay for a frontend error report service
- we could catch errors and send them to fauna or s3

If we want the latter, we could hook into React batching updates and catch any error, as described [here](https://engineering.classdojo.com/blog/2016/12/10/catching-react-errors/).

We would need a backend to send the errors to. Perhaps a simple option could be a lambda function at amazon so we could store the errors at s3 / fauna as well as send notifications to some channel in slack.

Thoughts?

**Comment by eaceaser** [comment]
If there's something that does this for us we should pay. Not sure what the state of the art is these days. Sentry? Airbrake?

**Comment by erickpintor** [comment]
I have to do more research. I have friends using Sentry.

**Comment by erickpintor** [comment]
Sentry seems to be the simplest one. There is also https://trackjs.com/ which seems to have more rich features for front end monitoring.

We don't need a lot right now. I'm happy if we hook sentry in. 
Their pricing model is a little confuse, though.

Maybe we should use the free trial and see how it goes.

**Comment by erickpintor** [comment]
Hight level tasks:

- [ ] Setup dashboard integration
- [ ] Fix NODE_ENV so we don't track staging environment
- [ ] Setup slack notifications
- [ ] Change deploy to tag releases
