### ISSUE TITLE
Error while rendering DateTime on query results

### ISSUE THREAD

**Issue by marrony** [fauna/dashboard#53]
The following error occurs when rendering `DateTime` on query result:

<img width="747" alt="DateTime bug" src="https://cloud.githubusercontent.com/assets/1334759/21768213/8a849d76-d65f-11e6-863f-b77aedc784a9.png">

**Comment by jchris** [comment]
Maybe look here for the problem code: https://github.com/faunadb/dashboard/blob/master/src/index-query/IndexQuery.js#L104

**Comment by erickpintor** [comment]
I think this was fixed. @marrony can provide the scenario for us to test?

**Comment by erickpintor** [comment]
Fixed.
