### ISSUE TITLE
move logout button to toolbar

### ISSUE THREAD

**Issue by jchris** [fauna/dashboard#56]
the toolbar at the bottom is currently just for repl stuff, but I think it should be more useful.

When the repl is closed it should look like this:

```
[ ( ^ Toggle Console)    / > my_db > nested_db > foo_db                        (Account) ]
```

Where account is a button that pops up a [CommandBar menu](https://dev.office.com/fabric#/components/commandbar) that contains "Log out", "Billing", "Admin Keys" etc.

When the REPL is open, the breadcrumb component should move *above the repl text area* and the additional REPL commands should appear where the breadcrumbs used to be.

```
[ ( v Toggle Console)    (Snippets)  (History) (Run)                       (Account) ]
```

**Comment by erickpintor** [comment]
I would advise to keep account information at the top right corner just because that is the first place people look for their account information. It has become a stablished pattern for web applications.

Though, the logout button totally need better styling.

**Comment by erickpintor** [comment]
We've implemented a dropdown menu at the header. I imagine that's the place where we can start adding account information for the logged in users.
