### ISSUE TITLE
Better pagination strategy for schema classes

### ISSUE THREAD

**Issue by erickpintor** [fauna/dashboard#77]
We're using `q.Paginate` function to read `databases`, `classes`, `indexes, etc. The problem is that we're just showing the first page which will limit us to only 16 elements of each schema class.

**Comment by erickpintor** [comment]
#78 could lead us to a generic approach to fix this.

**Comment by jchris** [comment]
I bet we could do something like have pagination arrows in the headers of the sections, like

```
Classes   <  >
```

Instead of the fold open and closed chevron we don't use right now.

**Comment by erickpintor** [comment]
We fixed this. We load all classes and indexes when the user selects the database so, when the user tries to create an index, for example, the source dropdown will be filled with all classes.
