### ISSUE TITLE
Instance form improvements

### ISSUE THREAD

**Issue by jchris** [fauna/dashboard#82]
The instance form claims to support Ref() and should probably support more. Maybe it would be less confusing to have a button there that populates a create statement for the current class into the REPL?

We also need a way to edit instances, currently it has to be done in the REPL...

**Comment by erickpintor** [comment]
@jchris what do you think about the way instances work now?
We have an instance view, we can see it's history, delete it and edit it's data field.

**Comment by jchris** [comment]
it is good
