### ISSUE TITLE
rate limiter for client infinite loops

### ISSUE THREAD

**Issue by jchris** [fauna/dashboard#84]
We used to replace the prototype network function with a no-op when the client had got more than 10 error responses back in 5 seconds.

I think this is good security to keep in the client. I've already found 2 bugs that hit the server with real load from a single laptop, that we'd find faster if the client screamed, and with less risk of users melting their laptops (and our servers) when they navigate wrong on the dashboard.

**Comment by erickpintor** [comment]
This has never happened on the new dashboard. I'm closing it for now.
