### ISSUE TITLE
route changes should dispatch

### ISSUE THREAD

**Issue by jchris** [fauna/dashboard#96]
the URL bar should be the source of truth for most link clicks. But today I had to leave in this call to dispatch or the UI didn't change properly:

```js
  navLinkClicked(e, link) {
    e.preventDefault();
    browserHistory.push(link.url)
    this.props.dispatch(link.action)
  }
```

**Comment by erickpintor** [comment]
Right changes on the routes are not triggering the required redux actions. We should fix that.

Refer to: https://faunadb.atlassian.net/wiki/display/SE/Schema+Tree+Hierarchy

**Comment by jchris** [comment]
on first pass it looks like `onChangeDatabase` is getting called when expected, but for some reason the classes and indexes aren't updating. Also looks like render NavSchema1 is getting called plenty of times, just not taking away the data. I'm still debugging this, just leaving notes here as I go.

**Comment by jchris** [comment]
related to #86 and #102 

current reproduction is browse to a database, create a sub database, and you'll be redirected to it, but the nav tree doesn't change.

**Comment by marrony** [comment]
Well, it does change, if you expand the component you'll see the new database there. To me the problem is the component that don't update itself accordingly

**Comment by jchris** [comment]
It's no the db-tree I'm thinking of, it's the schema (classes & indexes) that still represent the parent database, not the newly created one

**Comment by jchris** [comment]
IT looks like the issue is that the NavSchema fires its query using the old client, before the `@@client/UPDATE` call.

**Comment by jchris** [comment]
There is a race condition where `getAllIndexes` can be called while the database is still `path/to/parent`, but the query results are attached after a reset state call, where the database is now `path/to/parent/child`, so that we get inconsistent state.

The work around is to avoid triggering a requery until the database has been updated by the call in the router. The local code that was pushing to the history url was also reacting a button or something and triggering an early rerender / requery... I might have to get clever in componentWillReceiveProps if I want to avoid the early query.

We should beware that this race condition is a consequence of the redux pattern.

**Comment by marrony** [comment]
In this [pr](https://github.com/faunadb/dashboard/pull/112) I had refactored a little bit that condition

**Comment by jchris** [comment]
I think that I'm basically learning the code path now so I can understand the refactor. It's probably a good time for me to review your refactor again, since I have this in my head now.

**Comment by marrony** [comment]
that branch is rotted now and the workflow changed a bit, will have to rebase it on top of master before

**Comment by erickpintor** [comment]
This was fixed.
